# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 714ef237892f71c1e487929cf4650abd83bea2b93fba8928c4045c42e0d4b63c55ca6c4a8f3017b4980a447cd6d00577170b06ecd9df32883fc0aaf5f671c6f6

test:
  secret_key_base: f81082125e14314c19d283d927958b2f4ff61a0475d0d4ce7017e0a4ef9a51ea26594113d28cb636bffa61da800d25c846644521718cc2f4b413e884db3bb37c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
